#!/usr/bin/env python

from __future__ import print_function

import sys
from modelcobras import control

if len(sys.argv)==1:
    print ('''
Must specify a directory from which to read control map data 

> ./mk_tos1testing <Stage2/forward.lst output directory>
''')
    sys.exit ()
specdir = sys.argv[1]
if (specdir == '--help') or (specdir=='-h'):
    print ( '''Generate an MSIM file to move the stage 2 motors to 55 deg.

> ./mk_tos1testing <Stage2/forward.lst output directory>''')


control.moveto_stage1testing ( specdir )
print('Saved output to ./msim_scripts/moveto_stage1testing.lst')
